/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileEditor: typeof import('./src/components/FileEditor.vue')['default']
    GameOptions: typeof import('./src/components/GameOptions.vue')['default']
    GameOptionsGraphics: typeof import('./src/components/GameOptionsGraphics.vue')['default']
    GameOptionsInterface: typeof import('./src/components/GameOptionsInterface.vue')['default']
    GameOptionsSelection: typeof import('./src/components/GameOptionsSelection.vue')['default']
    GameOptionsSound: typeof import('./src/components/GameOptionsSound.vue')['default']
    GameOptionsSpeed: typeof import('./src/components/GameOptionsSpeed.vue')['default']
    OtherProfileSettings: typeof import('./src/components/OtherProfileSettings.vue')['default']
    ProfileTypeEditor: typeof import('./src/components/ProfileTypeEditor.vue')['default']
    ShieldValueDisplay: typeof import('./src/components/ShieldValueDisplay.vue')['default']
    ShortcutEditDialog: typeof import('./src/components/ShortcutEditDialog.vue')['default']
    Shortcuts: typeof import('./src/components/Shortcuts.vue')['default']
    StringsCollectionEditor: typeof import('./src/components/StringsCollectionEditor.vue')['default']
    UnitTemplates: typeof import('./src/components/UnitTemplates.vue')['default']
  }
}
